[package]
name = "file"
version = "0.1.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
description = "Convenience functions file::get() and file::put()"
license = "MIT"
repository = "https://github.com/pornel/rust-file.git"
readme = "README.md"
